import { CurrentUser } from '@/common/decorators/current-user.decorator';
import { JwtAuthGuard } from '@/common/guards/jwt-auth.guard';
import {
  Body,
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import { SkipThrottle, Throttle } from '@nestjs/throttler';
import { GenerateQrDto } from './dto/generate-qr.dto';
import { GetQrHistoryDto } from './dto/get-qr-history.dto';
import { VerifyPaymentDto } from './dto/verify-payment.dto';
import { PaymentGatewayGuard } from './guards/payment-gateway.guard';
import { PaymentsService } from './payments.service';

@Controller('admin/payments')
export class PaymentsController {
  constructor(private readonly paymentsService: PaymentsService) { }

  /**
   * POST /admin/payments/sample-order
   * Creates a demo order with sample items and immediately returns a QR code.
   *
   * Rate-limited: 5 per minute to prevent demo spam.
   */
  @Post('sample-order')
  @UseGuards(JwtAuthGuard)
  @Throttle({ short: { limit: 5, ttl: 60_000 } })
  async createSampleOrder(
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.createSampleOrder(currentUser.userId);
    return {
      success: true,
      data: result,
      message: 'Sample order created with QR code — valid for 2 minutes',
    };
  }

  /**
   * POST /admin/payments/generate-qr
   * Authenticated user generates a signed QR for one of their orders.
   * Any existing PENDING QR for the same order is cancelled first.
   *
   * Rate-limited: 10 per minute per user.
   */
  @Post('generate-qr')
  @UseGuards(JwtAuthGuard)
  @Throttle({ short: { limit: 10, ttl: 60_000 } })
  async generateQr(
    @Body() dto: GenerateQrDto,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.generateQr(dto, currentUser.userId);
    return {
      success: true,
      data: result,
      message: 'QR code generated — valid for 2 minutes',
    };
  }

  /**
   * POST /admin/payments/verify
   * Called by the payment gateway after the payer submits payment.
   *
   * Auth: X-Gateway-Key header — not JWT. The gateway is a machine client
   * that does not hold a user JWT; it identifies itself with a shared secret
   * configured via the PAYMENT_GATEWAY_KEY environment variable.
   *
   * Rate-limited: 20 per minute — tight cap to resist timing/brute-force.
   */
  @Post('verify')
  @HttpCode(HttpStatus.OK)
  @UseGuards(PaymentGatewayGuard)
  @Throttle({ short: { limit: 20, ttl: 60_000 } })
  async verifyPayment(@Body() dto: VerifyPaymentDto) {
    const result = await this.paymentsService.verifyAndProcess(dto);
    return {
      success: true,
      data: result,
      message: 'Payment verified and order confirmed',
    };
  }

  /**
   * GET /admin/payments/qr-history
   * Paginated list of all QR codes generated by the current user.
   * Stale PENDING records are auto-marked EXPIRED on each call.
   *
   * Query params: status, orderId, skip, limit
   */
  @Get('qr-history')
  @UseGuards(JwtAuthGuard)
  @SkipThrottle()
  async getQrHistory(
    @Query() dto: GetQrHistoryDto,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.getQrHistory(currentUser.userId, dto);
    return { success: true, data: result.data, total: result.total };
  }

  /**
   * GET /admin/payments/orders/:orderId/qr
   * Returns the current active (PENDING) QR for an order by orderId.
   * Returns { data: null } when no active QR exists.
   */
  @Get('orders/:orderId/qr')
  @UseGuards(JwtAuthGuard)
  @SkipThrottle()
  async getActiveQrForOrder(
    @Param('orderId') orderId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const data = await this.paymentsService.getActiveQrForOrder(orderId, currentUser.userId);
    return { success: true, data };
  }

  /**
   * GET /admin/payments/qr/:qrId
   * Full QR details including the rendered QR image (PENDING only).
   */
  @Get('qr/:qrId')
  @UseGuards(JwtAuthGuard)
  @SkipThrottle()
  async getQrById(
    @Param('qrId') qrId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const data = await this.paymentsService.getQrById(qrId, currentUser.userId);
    return { success: true, data };
  }

  /**
   * GET /admin/payments/qr/:qrId/status
   * Lightweight status-only poll (no QR image re-render).
   */
  @Get('qr/:qrId/status')
  @UseGuards(JwtAuthGuard)
  @SkipThrottle()
  async getQrStatus(
    @Param('qrId') qrId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const status = await this.paymentsService.getQrStatus(qrId, currentUser.userId);
    return { success: true, data: status };
  }
}
