import {
  Controller,
  Post,
  Get,
  Body,
  Param,
  Query,
  UseGuards,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { PaymentsService } from './payments.service';
import { GenerateQrDto } from './dto/generate-qr.dto';
import { GetQrHistoryDto } from './dto/get-qr-history.dto';
import { VerifyPaymentDto } from './dto/verify-payment.dto';
import { JwtAuthGuard } from '@/common/guards/jwt-auth.guard';
import { CurrentUser } from '@/common/decorators/current-user.decorator';

@Controller('admin/payments')
export class PaymentsController {
  constructor(private readonly paymentsService: PaymentsService) {}

  /**
   * POST /admin/payments/sample-order
   * Creates a demo order with sample items and immediately returns a QR code.
   * Useful for testing the full payment flow without manual setup.
   */
  @Post('sample-order')
  @UseGuards(JwtAuthGuard)
  async createSampleOrder(
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.createSampleOrder(currentUser.userId);
    return {
      success: true,
      data: result,
      message: 'Sample order created with QR code — valid for 10 minutes',
    };
  }

  /**
   * POST /admin/payments/generate-qr
   * Authenticated user generates a signed QR for one of their orders.
   */
  @Post('generate-qr')
  @UseGuards(JwtAuthGuard)
  async generateQr(
    @Body() dto: GenerateQrDto,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.generateQr(dto, currentUser.userId);
    return {
      success: true,
      data: result,
      message: 'QR code generated — valid for 10 minutes',
    };
  }

  /**
   * POST /admin/payments/verify
   * Called by the payment gateway after the payer submits payment.
   * No client auth required — gateway uses the embedded signed payload.
   */
  @Post('verify')
  @HttpCode(HttpStatus.OK)
  async verifyPayment(@Body() dto: VerifyPaymentDto) {
    const result = await this.paymentsService.verifyAndProcess(dto);
    return {
      success: true,
      data: result,
      message: 'Payment verified and order confirmed',
    };
  }

  /**
   * GET /admin/payments/qr-history
   * Returns a paginated list of all QR codes generated by the current user.
   * Supports optional filtering by status (pending | paid | expired | cancelled)
   * and by orderId. Stale PENDING records are auto-marked EXPIRED on each call.
   *
   * Query params:
   *   status   – filter by PaymentQrStatus
   *   orderId  – filter by order
   *   skip     – pagination offset (default 0)
   *   limit    – page size (default 20)
   */
  @Get('qr-history')
  @UseGuards(JwtAuthGuard)
  async getQrHistory(
    @Query() dto: GetQrHistoryDto,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const result = await this.paymentsService.getQrHistory(currentUser.userId, dto);
    return { success: true, data: result.data, total: result.total };
  }

  /**
   * GET /admin/payments/orders/:orderId/qr
   * Returns the current active (PENDING) QR for an order, looked up by orderId.
   * Useful when you have an orderId but not the qrId.
   * Returns { data: null } when no active QR exists for the order.
   */
  @Get('orders/:orderId/qr')
  @UseGuards(JwtAuthGuard)
  async getActiveQrForOrder(
    @Param('orderId') orderId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const data = await this.paymentsService.getActiveQrForOrder(orderId, currentUser.userId);
    return { success: true, data };
  }

  /**
   * GET /admin/payments/qr/:qrId
   * Returns full QR code details including the rendered QR image.
   * For PENDING QRs the image is re-rendered from the Redis-cached payload.
   * For expired / paid / cancelled QRs, qrImage is null.
   */
  @Get('qr/:qrId')
  @UseGuards(JwtAuthGuard)
  async getQrById(
    @Param('qrId') qrId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const data = await this.paymentsService.getQrById(qrId, currentUser.userId);
    return { success: true, data };
  }

  /**
   * GET /admin/payments/qr/:qrId/status
   * Lightweight status-only poll (no QR image re-render).
   */
  @Get('qr/:qrId/status')
  @UseGuards(JwtAuthGuard)
  async getQrStatus(
    @Param('qrId') qrId: string,
    @CurrentUser() currentUser: { userId: string },
  ) {
    const status = await this.paymentsService.getQrStatus(qrId, currentUser.userId);
    return { success: true, data: status };
  }
}
